version: '3'

services:
    clickhouse-zookeeper:
        image: zookeeper
        ports:
            - "2181:2181"
            - "2182:2182"
        container_name: clickhouse-zookeeper
        hostname: clickhouse-zookeeper

    clickhouse-01:
        image: yandex/clickhouse-server
        hostname: clickhouse-01
        container_name: clickhouse-01
        restart: on-failure
        ports:
            - 9001:9000
        volumes:
            - /home/clickhouse/config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
            - /home/clickhouse/config/users.xml:/etc/clickhouse-server/users.xml
            - /home/clickhouse/config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
            - /home/clickhouse/config/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
            - /home/key:/home
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper"

    clickhouse-02:
        image: yandex/clickhouse-server
        hostname: clickhouse-02
        container_name: clickhouse-02
        restart: on-failure
        ports:
            - 9002:9000
        volumes:
            - /home/clickhouse/config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
            - /home/clickhouse/config/users.xml:/etc/clickhouse-server/users.xml
            - /home/clickhouse/config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
            - /home/clickhouse/config/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
            - /home/key:/home
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        depends_on:
            - "clickhouse-zookeeper"

networks:
    default:
        external:
            name: clickhouse-net
