---
# tasks file for clickhouse_config_macros
- name: macros conf
  template:
    src: "macros.j2"
    dest: "/etc/clickhouse-server/config.d/macros_{{ item }}.xml"
    owner: clickhouse
    group: clickhouse
    mode: 0644
  loop:
    - clickhouse-01
    - clickhouse-02
  notify: restart-ssh

