---
- name: Create config metrika.xml
  hosts: serv
  become: yes
  become_user: root

  vars:
    rep_names:
      replika1: 
          "clickhouse-01"
      perlika2:
          "clickhouse-02"
    clickhouse_shards: 
      shard_name: Cluster_1

  tasks:
  - name: metrika conf
    template:
      src: "metrika.j2"
      dest: "/etc/clickhouse-server/config.d/clickhouse_metrika.xml"
      owner: clickhouse
      group: clickhouse
      mode: 0644
    notify: restart-ssh

  handlers:
  - name: restart-ssh
    service:
      name: "ssh"
      state: restarted
